### ISSUE TITLE
App asks to update to new version, even though latest version is installed

### ISSUE THREAD

**Issue by thewhitewolf17** [rajkumaar23/AmritaRepo#1]
## Bug
+ Double Checked and I'm on version 2.5 of the app 
+ Asks to update to latest version even though I'm on the latest, 2.5. 

## Screenshots
<img src="https://user-images.githubusercontent.com/34317373/52799979-e2d4ac80-30a0-11e9-8c3b-8881daf6adb1.jpg" width="300">
<img src="https://user-images.githubusercontent.com/34317373/52800048-00097b00-30a1-11e9-8c3b-89c987e0752e.jpg" width="300">

## Environment

Android Version : 9.0 Pie
App Version : 2.5

**Comment by rajkumaar23** [comment]
There was an issue with the API endpoint which is consumed by the app to check for the latest version. It is fixed now!
